source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '11.0'

target 'HZToolLib_Example' do
  pod 'HZToolLib', :path => '../'

  target 'HZToolLib_Tests' do
    inherit! :search_paths

    
  end
end
